_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_all/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101

  BACKBONE:
    FREEZE: False
    FREEZE_AT: 5

  RPN:
    POST_NMS_TOPK_TRAIN: 2000 # 1000
  PROPOSAL_GENERATOR:
    FREEZE: False

  ROI_HEADS:
    NAME: "DiscriminativeROIHeads"
    NUM_CLASSES: 20
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: False
    BATCH_SIZE_PER_IMAGE: 256  # 512
    POSITIVE_FRACTION: 0.5  # 0.25

DATASETS:
  TRAIN: ('coco_trainval_novel_10shot',)
  TEST: ('coco_test_novel',)

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (2000,)
  MAX_ITER: 3000
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 200

TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 500

OUTPUT_DIR: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_novel_10shot_mfa"